### ISSUE TITLE
i don't know what to do this 

### ISSUE THREAD

**Issue by yasuoganliang** [cyphunk/snifferjs#2]
[yujinsheng@haha snifferjs-master]$ sudo node sniffer.js enp2s0 ""
On linux please supply gateway address as argument

**Comment by cyphunk** [comment]
try:

    [yujinsheng@haha snifferjs-master]$ sudo node sniffer.js enp2s0 "" <GATEWAY_ADDRESS>

change <GATEWAY_ADDRESS> to the IP address of your upstream router. For example:

    [yujinsheng@haha snifferjs-master]$ sudo node sniffer.js enp2s0 "" 192.168.1.1


sorry, I realize the commandline arguments are perhaps not the most clear.
